name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        default: '1.0.0'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Yandex Container Registry
        run: docker login --username oauth --password "${{ secrets.YANDEX_CLOUD_TOKEN }}" cr.yandex

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no varnikova@51.250.34.228 << 'EOF'
            docker pull cr.yandex/crpiaftpish65qrcr3tg/app:1.0.0_latest
            docker stop $(docker ps -q --filter ancestor=cr.yandex/crpiaftpish65qrcr3tg/app)
            docker run -d -p 80:3000 cr.yandex/crpiaftpish65qrcr3tg/app:1.0.0_latest
          EOF