name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        default: '1.0.0'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Yandex Container Registry
        run: docker login --username oauth --password "${{ secrets.YANDEX_CLOUD_TOKEN }}" cr.yandex

      - name: Pull Docker image
        run: |
          docker pull cr.yandex/crpiaftpish65qrcr3tg/app:${{ github.event.inputs.version }}_latest

      - name: Deploy to Production Server
        run: docker run -p 80:3000 cr.yandex/crpiaftpish65qrcr3tg/app:${{ github.event.inputs.version }}_latest
