name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm ci
      - run: npm run lint
      - run: npm test
      - name: Build Docker image
        run: |
             docker build -t cr.yandex/crpiaftpish65qrcr3tg/app:${{ github.event.inputs.version }} .
             docker build -t cr.yandex/crpiaftpish65qrcr3tg/app:${{ github.event.inputs.version }}_latest .
      - name: Push Docker image
        run: |
          docker login --username oauth --password "${{ secrets.YANDEX_CLOUD_TOKEN }}" cr.yandex
          docker push cr.yandex/crpiaftpish65qrcr3tg/app:${{ github.event.inputs.version }}
          docker tag cr.yandex/crpiaftpish65qrcr3tg/app:${{ github.event.inputs.version }} cr.yandex/crpiaftpish65qrcr3tg/app:${{ github.event.inputs.version }}_latest
          docker push cr.yandex/crpiaftpish65qrcr3tg/app:${{ github.event.inputs.version }}_latest
      - name: Create Release Issue
        uses: actions-ecosystem/action-create-issue@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: Release ${{ github.run_number }}
          body: |
            Release date: ${{ github.event.date }}
            Author: ${{ github.actor }}
            Version: ${{ github.run_number }}
            Docker image: cr.yandex/crpiaftpish65qrcr3tg/app:${{ github.run_number }}
